name: Publish Docker
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@master
      # Retrieve the latest tag to use as MAVSDK release tag.
      - name: Set MAVSDK release tag
        run: export MAVSDK_TAG="$(shell git describe --tags --abbrev=0 2>/dev/null || echo "v1.4.4")"
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      # https://github.com/marketplace/actions/docker-login
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      # https://github.com/marketplace/actions/docker-metadata-action
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            sitin/mavsdk
          # Configure tags:
          #   `master` branch -> `latest`
          #   `v{xx.yy.zz}` tag -> `{xx.yy.zz}`
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          # Supported platforms
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v6,linux/arm/v7
          # Build args
          build-args: MAVSDK_TAG
          # Do not push for pull requests
          push: ${{ github.event_name != 'pull_request' }}
          # Tags and labels defined in `meta` step
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
